# Generate protobuf go files from money_movement.proto template
generate-proto:
  protoc \
    --go_out . \
    --go_opt paths=source_relative \
    --go-grpc_out . \
    --go-grpc_opt paths=source_relative \
    proto/money_movement_svc.proto

  mkdir -p ../api_gateway/money_movement/proto
  cp proto/* ../api_gateway/money_movement/proto
