# Generate auth protobuf go files from auth_svc.proto template
generate-proto:
  protoc \
    --go_out . \
    --go_opt paths=source_relative \
    --go-grpc_out . \
    --go-grpc_opt paths=source_relative \
    proto/auth_svc.proto
