// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/money_movement_svc.proto

package pb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizePayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CustomerUserId string                 `protobuf:"bytes,1,opt,name=customerUserId,proto3" json:"customerUserId,omitempty"`
	MerchantUserId string                 `protobuf:"bytes,2,opt,name=merchantUserId,proto3" json:"merchantUserId,omitempty"`
	Paise          int64                  `protobuf:"varint,3,opt,name=paise,proto3" json:"paise,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizePayload) Reset() {
	*x = AuthorizePayload{}
	mi := &file_proto_money_movement_svc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePayload) ProtoMessage() {}

func (x *AuthorizePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_money_movement_svc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePayload.ProtoReflect.Descriptor instead.
func (*AuthorizePayload) Descriptor() ([]byte, []int) {
	return file_proto_money_movement_svc_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePayload) GetCustomerUserId() string {
	if x != nil {
		return x.CustomerUserId
	}
	return ""
}

func (x *AuthorizePayload) GetMerchantUserId() string {
	if x != nil {
		return x.MerchantUserId
	}
	return ""
}

func (x *AuthorizePayload) GetPaise() int64 {
	if x != nil {
		return x.Paise
	}
	return 0
}

type AuthorizeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthorizeResponse) Reset() {
	*x = AuthorizeResponse{}
	mi := &file_proto_money_movement_svc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizeResponse) ProtoMessage() {}

func (x *AuthorizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_money_movement_svc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizeResponse.ProtoReflect.Descriptor instead.
func (*AuthorizeResponse) Descriptor() ([]byte, []int) {
	return file_proto_money_movement_svc_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizeResponse) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

type CapturePayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Pid            string                 `protobuf:"bytes,1,opt,name=pid,proto3" json:"pid,omitempty"`
	CustomerUserId string                 `protobuf:"bytes,2,opt,name=customerUserId,proto3" json:"customerUserId,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CapturePayload) Reset() {
	*x = CapturePayload{}
	mi := &file_proto_money_movement_svc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePayload) ProtoMessage() {}

func (x *CapturePayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_money_movement_svc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePayload.ProtoReflect.Descriptor instead.
func (*CapturePayload) Descriptor() ([]byte, []int) {
	return file_proto_money_movement_svc_proto_rawDescGZIP(), []int{2}
}

func (x *CapturePayload) GetPid() string {
	if x != nil {
		return x.Pid
	}
	return ""
}

func (x *CapturePayload) GetCustomerUserId() string {
	if x != nil {
		return x.CustomerUserId
	}
	return ""
}

var File_proto_money_movement_svc_proto protoreflect.FileDescriptor

const file_proto_money_movement_svc_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/money_movement_svc.proto\x1a\x1bgoogle/protobuf/empty.proto\"x\n" +
	"\x10AuthorizePayload\x12&\n" +
	"\x0ecustomerUserId\x18\x01 \x01(\tR\x0ecustomerUserId\x12&\n" +
	"\x0emerchantUserId\x18\x02 \x01(\tR\x0emerchantUserId\x12\x14\n" +
	"\x05paise\x18\x03 \x01(\x03R\x05paise\"%\n" +
	"\x11AuthorizeResponse\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\"J\n" +
	"\x0eCapturePayload\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\tR\x03pid\x12&\n" +
	"\x0ecustomerUserId\x18\x02 \x01(\tR\x0ecustomerUserId2\x82\x01\n" +
	"\x14MoneyMovementService\x124\n" +
	"\tAuthorize\x12\x11.AuthorizePayload\x1a\x12.AuthorizeResponse\"\x00\x124\n" +
	"\aCapture\x12\x0f.CapturePayload\x1a\x16.google.protobuf.Empty\"\x00BAZ?github.com/d-Bharti001/go-payment-micro/money_movement/proto/pbb\x06proto3"

var (
	file_proto_money_movement_svc_proto_rawDescOnce sync.Once
	file_proto_money_movement_svc_proto_rawDescData []byte
)

func file_proto_money_movement_svc_proto_rawDescGZIP() []byte {
	file_proto_money_movement_svc_proto_rawDescOnce.Do(func() {
		file_proto_money_movement_svc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_money_movement_svc_proto_rawDesc), len(file_proto_money_movement_svc_proto_rawDesc)))
	})
	return file_proto_money_movement_svc_proto_rawDescData
}

var file_proto_money_movement_svc_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proto_money_movement_svc_proto_goTypes = []any{
	(*AuthorizePayload)(nil),  // 0: AuthorizePayload
	(*AuthorizeResponse)(nil), // 1: AuthorizeResponse
	(*CapturePayload)(nil),    // 2: CapturePayload
	(*emptypb.Empty)(nil),     // 3: google.protobuf.Empty
}
var file_proto_money_movement_svc_proto_depIdxs = []int32{
	0, // 0: MoneyMovementService.Authorize:input_type -> AuthorizePayload
	2, // 1: MoneyMovementService.Capture:input_type -> CapturePayload
	1, // 2: MoneyMovementService.Authorize:output_type -> AuthorizeResponse
	3, // 3: MoneyMovementService.Capture:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_money_movement_svc_proto_init() }
func file_proto_money_movement_svc_proto_init() {
	if File_proto_money_movement_svc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_money_movement_svc_proto_rawDesc), len(file_proto_money_movement_svc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_money_movement_svc_proto_goTypes,
		DependencyIndexes: file_proto_money_movement_svc_proto_depIdxs,
		MessageInfos:      file_proto_money_movement_svc_proto_msgTypes,
	}.Build()
	File_proto_money_movement_svc_proto = out.File
	file_proto_money_movement_svc_proto_goTypes = nil
	file_proto_money_movement_svc_proto_depIdxs = nil
}
